---
title: "Introducción a RStudio"
date: '2021-10-05T21:13:14-05:00'
categories: R
tags:
- R
- RStudio
output:
  blogdown::html_page:
    toc: true
type: book
weight: 20
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Recordemos que `RStudio` no es `R`. Es un programa que ejecuta `R` y proporciona herramientas adicionales que son útiles al escribir código `R`, algo así como su sistema operativo puede ejecutar un navegador web. 

Este taller asumirá que estamos utilizando `RStudio` para interactuar con `R`, aunque todo lo que veremos se puede hacer directament en `R`.

# 1. Instalación de `RStudio`
`RStudio` es gratuito y de código abierto. Haz clic [aquí](https://www.rstudio.com/products/rstudio/download/) para descargar la versión que corresponda a tu sitema operativo.

`RStudio` requiere la instalación de `R` (versión 3.0. 1 o superior). Para descargar `R`, haz clic [aquí](https://cran.r-project.org/bin/windows/base/) si tu sistema operativo es Windows, y [aquí](https://cran.r-project.org/bin/macosx/) en caso de que sea macOS.

# 2. Entorno de trabajo de `RStudio`
Cuando abras RStudio, notarás una ventana con cuatro paneles principales, cada uno con algunas pestañas.


## 2.1. Consola
En el panel inferior izquierdo, encontraremos la consola de `RStudio`. Es aquí donde podemos escribir las lineas de comando para interactuar con `R`, y en donde nuestro código es interpretado. La consola es la única parte de `RStudio` que en realidad es `R`; todo lo demás son herramientas opcionales.

  
## 2.2. Script
En el panel superior izquierdo, encontraremos el script, editor de texto con la extensión de archivo *.R* que puede ser leido por `R`. En el script escribiremos comandos que serán ejecutados en la consola. Además, en el script podemos agregar comentarios. Para ello, la(s) línea(s) de texto debe(n) estar precedidas por el el símbolo *#*.

Para guardar el script:

  + *File > Save as* y seleccionar la ruta donde se quiere guardar el archivo con la extensión *.R*
  + Hacer clic en el botón *Guardar* que se encuentra en la parte izquierda de la cinta de opciones del script.


## 2.3. Ambiente, Historial, Conecciones y Tutorial
En el panel superior derecho, encontraremos cuatro pestañas:

  + **Environment**: En el ambiente de trabajo se irán registrando el trabajo realizado (resultados, variables, gráficos, etc.) durante una determinada sesión. También tenemos la opción de cargar y guardar una sesión de trabajo, importar datos y limpiar los objetos de la sesión.
  + **History**: En el hisotrial se registran las instrucciones ejecutadas. Como opciones, podemos cargar y guardar el historial de la sesión, seleccionar una o más instrucciones y enviarlas a la consola o al script, además de poder limpiar el historial.
  + **Connections**: En conecciones,  puedes conectar `RStudio` a diferentes fuentes de datos. Por ejemplo ODBC, Spark, Oracle, SQLServer, entre otras.
  + **Tutorial**: Aquí encontraremos ayuda usando el paquete `learnr`.


## 2.4. Archivos, Visualizaciones, Paquetes y Ayuda
En el panel inferior derecho, encontraremos cuatro pestañas:

+ **Files**: En la pestaña archivos podemos ver el historial de archivos trabajados.
+ **Plots**: Aquí se visualizan los gráficos que generamos. 
+ **Packages**: Entrega un listado de los paquetes instalados en `R` y los que han sido cargados en la sesión. A través de las opciones de esta pestaña podemos instalar nuevos paquetes o actualizar los existentes.
+ **Help**: Permite acceder al CRAN (siempre que se cuente con conexión a Internet), página oficial del software que ofrece diferentes recursos para el programa: información general,  de los paquetes instalados, de funciones de interés, entre otros.

Es importante señalar que podemos reorganizar los paneles en *Ver -> Paneles -> Diseño de panel*. Además. podemos agregar y eliminar pestañas de los paneles en *Ver* y seleccionando o deseleccionando las opciones de pestañas que se enumeran en la parte inferior.

# 3. Interactuando con `RStudio`
Interactuar con `RStudio` es simple. Básicamente, debemos escribir el código `R` en la línea inferior de la consola y luego haga clic en *Enter* para ejecutarlo. También podemos enviar código desde el *script*, presionando *<Ctrl + R>* (Windows) o *<Ctrl +Enter>* (Mac).

El código que escribimos se llama comando, porque dará la orden a nuestro computador que haga algo por nosotros. La línea en la que escribimos se llama línea de comando.

Cuando escribimos un comando en el prompt *>* y presionamos *Enter*, o lo enviamos desde el *script*, `R` ejecutará el comando y nos mostará los resultados en la consola. Junto a nuestros resultados, aparecerá *[1]*, informando que en esta línea comienza con el primer valor del resultado. Luego, RStudio muestra un nuevo *>* para su próximo comando.

Es importante tener en cuenta que:
  
  + Cuando la consola muestra el prompt *>*, significa que podemos dar nuevos comandos para ejecutar.
  + Si escribimos un comando incompleto y presionamos *Enter*, la consola mostrará un indicador *+*, lo que significa que está esperando que escribamos el resto del comando. 
  + Si escribimos un comando que R no reconoce, R devolverá un mensaje de error. Esto no es para alarmarno. R simplemente nos está diciendo que no puede entender o hacer lo que le pedimos. El texto en rojo nos avisa y explica, los errores en la solicitud realizada.


# 5. Sintáxis
`R` es un lenguaje de programación. Tanto en `R`, así como de la interfaz `RStudio`, podemos  interactuará con el programa mediante códigos. La sintaxis es un conjunto de códigos. Su uso en `R` y `RStudio` es bastante intuitivo y sigue un patrón lógico. 

De modo general, la sintáxis de `R` sigue la siguiente estructura básica:

`comando(objeto)`

En donde:

* `comandos`: función a ejecutar a un objeto.

* `objeto`: estructura de datos que tiene algunos atributos y métodos que actúan sobre sus atributos.

Este ejemplo es una operación simple. Al aumentar la complejidad de los análisis la especificación de los comandos y los objetos irá requiriendo una mayor cantidad de información.
